language: r
cache: packages
latex: false
fortran: false
r_build_args: '--no-build-vignettes'

matrix:
  include:
    - env: _R_CHECK_FORCE_SUGGESTS_=0
      dist: precise
      r_check_args: '--ignore-vignettes'
      addons:
        apt:
          packages:
            - libmagick++-dev
            - librsvg2-dev
            - libwebp-dev
            - libpoppler-cpp-dev
            - libfftw3-dev
      before_install:
        - sudo rm -f /usr/share/doc/libmagick++-dev
        - sudo rm -f /usr/share/doc/imagemagick-common
        - sudo add-apt-repository -y ppa:opencpu/imdev
        - sudo apt-get update -y
        - sudo apt-get install libmagick++-dev -y
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.1
      brew_packages: imagemagick
      env: R_CODECOV=true
    - os: osx
      latex: false
      osx_image: xcode9.1
      brew_packages: imagemagick@6 --with-fontconfig --with-webp --with-librsvg --with-fftw
    - os: osx
      osx_image: xcode9.1
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev

bioc_packages:
  - EBImage

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov(type = "all")'; fi

# Prevents Travis timeout for building magick
before_install:
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &
